version: '2'
volumes:
  resin-data:
services:
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  store-and-forward:
    build: ./bubblesgrpc-server
    privileged: true
    restart: always
    depends_on:
    - wifi-connect
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    volumes:
    - 'resin-data:/data'
    - 'resin-data:/config'
    ports:
    - "50051:50051"
    - "8080:8080"
