# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bubblesgrpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62ubblesgrpc.proto\x12\x0b\x62ubblesgrpc\"@\n\rSensorRequest\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"Q\n\x0bSensorReply\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"B\n\x0fGetStateRequest\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\xb9\x01\n\rGetStateReply\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x17\n\x0ftemp_air_middle\x18\x04 \x01(\x02\x12\x19\n\x11humidity_internal\x18\x05 \x01(\x02\x12\x15\n\rtemp_external\x18\x06 \x01(\x02\x12\x12\n\ntemp_water\x18\x07 \x01(\x02\x12\x16\n\x0elight_internal\x18\x08 \x01(\x02\"G\n\x14GetRecordListRequest\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"U\n\x12GetRecordListReply\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t2\x81\x02\n\x15SensorStoreAndForward\x12I\n\x0fStoreAndForward\x12\x1a.bubblesgrpc.SensorRequest\x1a\x18.bubblesgrpc.SensorReply\"\x00\x12\x46\n\x08GetState\x12\x1c.bubblesgrpc.GetStateRequest\x1a\x1a.bubblesgrpc.GetStateReply\"\x00\x12U\n\rGetRecordList\x12!.bubblesgrpc.GetRecordListRequest\x1a\x1f.bubblesgrpc.GetRecordListReply\"\x00\x42\x30\n\x1aorg.bubblesnet.bubblesgrpcB\x10\x42ubblesGRPCProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bubblesgrpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.bubblesnet.bubblesgrpcB\020BubblesGRPCProtoP\001'
  _SENSORREQUEST._serialized_start=34
  _SENSORREQUEST._serialized_end=98
  _SENSORREPLY._serialized_start=100
  _SENSORREPLY._serialized_end=181
  _GETSTATEREQUEST._serialized_start=183
  _GETSTATEREQUEST._serialized_end=249
  _GETSTATEREPLY._serialized_start=252
  _GETSTATEREPLY._serialized_end=437
  _GETRECORDLISTREQUEST._serialized_start=439
  _GETRECORDLISTREQUEST._serialized_end=510
  _GETRECORDLISTREPLY._serialized_start=512
  _GETRECORDLISTREPLY._serialized_end=597
  _SENSORSTOREANDFORWARD._serialized_start=600
  _SENSORSTOREANDFORWARD._serialized_end=857
# @@protoc_insertion_point(module_scope)
