# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bubblesgrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bubblesgrpc.proto',
  package='bubblesgrpc',
  syntax='proto3',
  serialized_options=_b('\n\025com.farlo.bubblesgrpcB\020BubblesGRPCProtoP\001'),
  serialized_pb=_b('\n\x11\x62ubblesgrpc.proto\x12\x0b\x62ubblesgrpc\"@\n\rSensorRequest\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"Q\n\x0bSensorReply\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07type_id\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t2b\n\x15SensorStoreAndForward\x12I\n\x0fStoreAndForward\x12\x1a.bubblesgrpc.SensorRequest\x1a\x18.bubblesgrpc.SensorReply\"\x00\x42+\n\x15\x63om.farlo.bubblesgrpcB\x10\x42ubblesGRPCProtoP\x01\x62\x06proto3')
)




_SENSORREQUEST = _descriptor.Descriptor(
  name='SensorRequest',
  full_name='bubblesgrpc.SensorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='bubblesgrpc.SensorRequest.sequence', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='bubblesgrpc.SensorRequest.type_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='bubblesgrpc.SensorRequest.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=98,
)


_SENSORREPLY = _descriptor.Descriptor(
  name='SensorReply',
  full_name='bubblesgrpc.SensorReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='bubblesgrpc.SensorReply.sequence', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='bubblesgrpc.SensorReply.type_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='bubblesgrpc.SensorReply.result', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='bubblesgrpc.SensorReply.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['SensorRequest'] = _SENSORREQUEST
DESCRIPTOR.message_types_by_name['SensorReply'] = _SENSORREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorRequest = _reflection.GeneratedProtocolMessageType('SensorRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENSORREQUEST,
  '__module__' : 'bubblesgrpc_pb2'
  # @@protoc_insertion_point(class_scope:bubblesgrpc.SensorRequest)
  })
_sym_db.RegisterMessage(SensorRequest)

SensorReply = _reflection.GeneratedProtocolMessageType('SensorReply', (_message.Message,), {
  'DESCRIPTOR' : _SENSORREPLY,
  '__module__' : 'bubblesgrpc_pb2'
  # @@protoc_insertion_point(class_scope:bubblesgrpc.SensorReply)
  })
_sym_db.RegisterMessage(SensorReply)


DESCRIPTOR._options = None

_SENSORSTOREANDFORWARD = _descriptor.ServiceDescriptor(
  name='SensorStoreAndForward',
  full_name='bubblesgrpc.SensorStoreAndForward',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=183,
  serialized_end=281,
  methods=[
  _descriptor.MethodDescriptor(
    name='StoreAndForward',
    full_name='bubblesgrpc.SensorStoreAndForward.StoreAndForward',
    index=0,
    containing_service=None,
    input_type=_SENSORREQUEST,
    output_type=_SENSORREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORSTOREANDFORWARD)

DESCRIPTOR.services_by_name['SensorStoreAndForward'] = _SENSORSTOREANDFORWARD

# @@protoc_insertion_point(module_scope)
