name: edge-device-ci

on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: '45 08 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build BubbleGPRC
        working-directory: store-and-forward/bubblesgrpc-server
        run: go build -v ./...

      - name: Test BubblesGRPC
        working-directory: store-and-forward/bubblesgrpc-server
        run: |
          go test -coverprofile=coverage.out -v ./...
          bash <(curl -s https://codecov.io/bash) -t bd6757f7-5f19-40b6-81f3-68547d5b9177 -v

      - name: Build Sense Go
        working-directory: sense-go
        run: go build -v ./...

      - name: Test Sense Go
        working-directory: sense-go
        run: |
          go test -coverprofile=coverage.out -v ./...
          bash <(curl -s https://codecov.io/bash) -t bd6757f7-5f19-40b6-81f3-68547d5b9177 -v

      - name: Setup Sense-Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Test sense-python
        working-directory: sense-python/src
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install -r requirements.txt
          pipenv install pytest
          pipenv install --dev
