name: Go

on:
  push:
    branches: [ 1-feature-setup, develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Sense Go
      working-directory: sense-go
      run: go build -v ./...

    - name: Test Sense Go
      working-directory: sense-go
      run: go test -v ./...

    - name: Build BubbleGPRC
      working-directory: store-and-forward/bubblesgrpc-server
      run: go build -v ./...

    - name: Test BubblesGRPC
      working-directory: store-and-forward/bubblesgrpc-server
      run: go test -v ./...
